"""add discount system

Revision ID: 7bf734510219
Revises: f3bf327fdd60
Create Date: 2026-02-16 17:41:48.239853

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7bf734510219'
down_revision: Union[str, Sequence[str], None] = 'f3bf327fdd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
