"""Add discount system

Revision ID: f2664f359a40
Revises: 
Create Date: 2026-02-17 00:48:50.256010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2664f359a40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=True)
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('discount_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'discount_code')
    op.drop_column('orders', 'subtotal')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_table('discounts')
    # ### end Alembic commands ###
