"""complete discount system

Revision ID: f56d313f083e
Revises: 7bf734510219
Create Date: 2026-02-16 17:43:29.337209

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f56d313f083e'
down_revision: Union[str, Sequence[str], None] = '7bf734510219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
